### ISSUE TITLE
关于文件上传模块的问题咨询

### ISSUE THREAD

**Issue by Alvazz** [pddzl/td27-admin#7]
感谢老哥开源这么简洁有力的项目，我看到后台有个支持文件上传的功能，那么请问如果我上传的是图片，该怎么弄才能从前端浏览器里访问这张图片呢？

**Comment by pddzl** [comment]
放到nginx的资源目录下面

**Comment by pddzl** [comment]
> 感谢老哥开源这么简洁有力的项目，我看到后台有个支持文件上传的功能，那么请问如果我上传的是图片，该怎么弄才能从前端浏览器里访问这张图片呢？

放到nginx的资源目录里面

**Comment by Alvazz** [comment]
具体怎么搞啊？我看代码里有个 resource/upload目录啊，这个目录就说你说的nginx资源目录吗？

**Comment by pddzl** [comment]
把上传目录设置成nginx的资源目录
